### ISSUE TITLE
polycosm_boot.shが修正無効

### ISSUE THREAD

**Issue by shihaodongfenrir** [kou029w/zenn.dev#1]
reticulumデポロイ方法を拝見して最後までデポロイできました。ありがとうございます！

但し、公式手順により、[hubscluodをofflineモードに変更](https://hubs.mozilla.com/docs/hubs-cloud-aws-costs.html#offline-mode---manual)して、onlineモードに切り替えると、下記の修正した**polycosm_boot.sh**ファイルを元に戻った現象が存在しています。
申し訳ございませんが、何日この難題にはまってしまいまして、何とかヒントがございましたら、教えていただけませんか？

```
# 起動スクリプトの改変: kou029w/reticulum を読み込んで実行されるように変更
sudo perl -i -pe 's(\b(mozillareality/reticulum)\b)(kou029w/reticulum)g' /opt/polycosm/polycosm_boot.sh

# 起動スクリプトの改変: 起動スクリプト実行時のインスタンス名の変更に伴う証明書の更新対応
sudo perl -i -pe 's/^(ln -s)\b/ln -sf/' /opt/polycosm/polycosm_boot.sh
```

**Comment by kou029w** [comment]
@shihaodongfenrir
実際に試してくださりありがとうございます。
なるほど、オフラインモードで運用するとファイルが元の状態に戻るわけですね。
説明には特に書いていないため大変申し訳ないのですが、実は常時起動 (お金がかかる…) で運用する想定で手順を書いており、そのあたりの、EC2インスタンスがTerminateされる、あるいはインスタンスがスケールアップされる、ヘルスチェックに失敗して再構築されるなど、いくつかHubs Cloudのデフォルトの挙動 (これはCloudFormationテンプレート内に宣言されているもの) によってインスタンスの内部が初期化されうる問題があります。
つまり、インスタンスが立ち上がるたびに毎回差し替えが必要な手順になっております。すみません。
実際のところどのようにすると良いか私には判断つきません。

もし仮に対処するとなると、たとえばCloudFormationテンプレート内に宣言されている`/opt/polycosm/polycosm_boot.sh` という起動スクリプトの指定の直前に起動スクリプトの改変処理に書き換える、あるいは起動中のインスタンスのスナップショットをAMIとして保存しそのIDをCloudFormationテンプレート内で現在指定されているEC2のAMI IDを上書きする、等、でしょうか。ただし後者は自分でも試した記憶がありますがなにか上手くいかなかったです。。。前者は試していないです。

当時のメモ:

> 2020年11月12日 (JST):
> EC2 > EBS > ボリューム > スナップショットの作成 > 作成
> EC2 > EBS > スナップショット > (EBS スナップショットから) イメージを作成 > 名前: "ahiru17" > 作成
> EC2 > イメージ > AMI > 新しく作成されたAMI IDを読む
> CloudFormation > スタック > テンプレート > "ImageId" とある部分のパラメータをすべて作成したAMI IDに書き換えたファイルを作成しローカルに保存
> CloudFormation > スタック > 既存スタックの変更セットを作成 > 既存テンプレートを置き換える > テンプレートファイルのアップロード > 書き換えたテンプレートファイルを選択 > 作成
> CloudFormation > スタック > 変更セット > 実行
> 
> … が新しく作られたEC2インスタンスの中の起動時のログを読むとcerts, pgBouncer, Janus あたりのサービスが正常に機能しておらず、cfn-signalが送られず、CloudFormationの変更セットが30分後にタイムアウトされロールバック。むふー。
> なかなか厳しそう。。。 > AMIの作成とAppLaunchConfigurationの書き換え

このあたりの問題はそもそもpolycosm_boot.shなどインフラ構築周りのコードの生成プロセスをMozillaが公開していないため、どうしても場当たり的な対処になってしまっており、なかなか厳しいところではあります。

…という感じです! 私自身も問題を整理しきれておらずいろいろと説明不足あったかと思うので申し訳ないのですが、もしなにか参考になれば幸いです :bow:

**Comment by shihaodongfenrir** [comment]
@kou029w 
早速回答ありがとうございます！

スゴく勉強になりました。これからの調査方向ははっきり理解できました。ありがとうございます。
`EC2インスタンスがTerminateされる、あるいはインスタンスがスケールアップされる、ヘルスチェックに失敗して再構築されるなど、いくつかHubs Cloudのデフォルトの挙動 (これはCloudFormationテンプレート内に宣言されているもの) によってインスタンスの内部が初期化されうる問題があります。`
CloudFormationテンプレートは下記のファイルですよね。
https://github.com/mozilla/hubs-ops/blob/master/cloudformation/stack.yaml
テンプレート内容をまだ理解中なので、理解した上に検討させていただきます。

アドバイスと当時のメモは本当に助かりました。
参考にしてチャレンジしてみます。
