### ISSUE TITLE
reticulumをデプロイするも、リソースが読み込めない

### ISSUE THREAD

**Issue by ryo-89287** [kou029w/zenn.dev#2]
現在、ご執筆いただきました記事を参考にreticulumをデプロイすることができました！
大変参考になりました。ありがとうございます！

ですが、私の環境ですと、下記のエラーが表示されて、管理画面からアップロードしたロゴ画像などのリソースが読み込めないです。

Failed to load resource: the server responded with a status of 403

環境構築を行う際に、この辺りで参考になるようなことはありますでしょうか？
よろしくお願いいたします。

**Comment by kou029w** [comment]
@ryo-89287
私が当時試した範囲ではそういった問題は確認していないので最近の変更に伴う影響かもしれないですね。
…というわけで本家のIssue・PRを見てみました。 https://github.com/mozilla/hubs/pull/4565 こちらのPRの内容がもしかしたら似たような問題の解決になるかもしれません。しかし私のほうでは最近は試していないので問題の詳細を確認できないため解決手段などに関する詳細はこれ以上はすみませんが分からないです。本家の[Contributing · Hubs by Mozilla](https://hubs.mozilla.com/docs/contributing.html)を参考にしてMozillaのコミュニティのほうにご相談いただければと思います。

**Comment by ryo-89287** [comment]
@kou029w さん
ご返信ありがとうございます。
頂きましたPRのページを確認すると、それ以前のバージョンが自分の作業環境でした。
一度、最新版にアップデートして試してみます。

試せるものは全部試していたので、大変参考になりました！
ありがとうございます！！
