### ISSUE TITLE
Deployment stays at Waiting for Janus

### ISSUE THREAD

**Issue by angelcabrera-nr** [kou029w/zenn.dev#3]
Hello, I want to thank you in advance because your tutorial helped me deploy changes to my Mozilla Hubs server.

However, yesterday, trying to redeploy, the process gets stuck on Waiting for Janus and doesn't progress any further, the service in supervisor is UP but still doesn't progress the deployment, and because of that the microphone services don't work in rooms.

Do you have any idea what could be happening or how I can solve this problem?

![image](https://user-images.githubusercontent.com/73490994/189495190-8241b77b-051b-455d-ac08-4fc02e55aebf.png)

**Comment by kou029w** [comment]
Sorry, I don't know of a solution. At least I didn't have that problem when I tried at the time. It may be an effect of the recent changes.
